# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: unittest

on: workflow_dispatch

jobs:

  unittest:
    runs-on: windows-latest
    steps:
      - name: test_base
        run: |
          git clone https://github.com/Juntongkuki/tnlearn_actions
          cd tnlearn_actions/tests

      - name: install unittest
        run: pip install unittest
    
