# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: unittest

on: workflow_dispatch

jobs:

  unittest:
    runs-on: windows-latest
    steps:
      - name: test_base
        run: |
          git clone https://github.com/Juntongkuki/tnlearn_actions
          cd tnlearn_actions
          cd tests
          python print.py
          python -m unittest test_base
          
      - name: install
        run: |
          pip install h5py~=3.10.0
          pip install numpy~=1.26.2
          pip install tnlearn~=0.1
          pip install torch~=2.1.0
          pip install sympy~=1.12
          pip install setuptools~=68.0.0
          pip install scikit-learn~=1.4.0
          pip install scipy~=1.12.0
          pip install joblib~=1.3.2
          pip install requests~=2.31.0
          pip install networkx~=3.2.1
          pip install matplotlib~=3.8.3
          pip install pandas~=2.2.0
          pip install packaging~=23.2
          pip install ipython~=8.18.1
          pip install tqdm~=4.66.2
          
      - name: test_base.py
        run: |
          cd tests
          python -m unittest test_base

    
